---
- name: Update web servers
  hosts: 13.48.24.249
  remote_user: ec2-user
  become_method: sudo
  become: true

  tasks:
    - name: Install Docker
      package:
        name: docker
        state: latest
    - name: service docker
      service:
        name=docker
        state=started
        enabled=yes

    - name: install docker compose
      ansible.builtin.shell: |
        curl -SL https://github.com/docker/compose/releases/download/v2.14.2/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
        sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Install GIT
      package:
        name: git
        state: latest

    - name: Download the weatherapp code from the GitRepo
      become: yes
      git:
        repo: 'https://github.com/PiyushHarne/weatherapp.git'
        dest: "weatherapp"

    - name: run docker compose
      ansible.builtin.shell: |
        cd weatherapp && sudo /usr/local/bin/docker-compose up -d --build
